### PR TITLE
Add Cobertura support

### PR DESCRIPTION
**Pull request by fernandrone**
Provide implementation for stubbed out Cobertura parser.

### CODE REVIEW

**Comment by fernandrone** [comment]
See: https://discuss.drone.io/t/aircover-python-coverage-support-cobertura/341

As it was suggested in the thread above, gave a try in implementing coverage support.

I'm still planning to set up a drone and aircover personal server so I can test this out though, but I thought it'd be better to submit the PR for review anyway

**Comment by fernandrone** [comment]
So, I've got my own aircover server running. I've built an image using this branch and I'm using it on my drone server to test out a python project: http://www.fbcbarbosa.xyz:8082/fbcbarbosa/superlists

Tests were run using nosetests with coverage plugin, which can create cobertura-like reports. Seems to be working fine - except for the fact that it ignores line #1:

image

The unit tests are being applied on junit and golang test reports. There seems to be multiple different headers for coverage files though, so I can't be sure it is compatible with every cobertura-like test report.

**Review by donny-dont — CHANGES_REQUESTED** [review]
Fix the tests and I think this is about ready to go.

**Comment by fernandrone** [comment]
Hi @donny-dont , thanks for commenting, I had kind of forgotten about this PR! Got the UTs fixed :+1: 

By the way, the previous comments still apply. Aircover continues to ignore the first line.

> The unit tests are being applied on junit and golang test reports. There seems to be multiple different headers for coverage files though, so I can't be sure it is compatible with every cobertura-like test report.

About this, I've tested this with Junit examples (found online), golang coverage files converted with gocov-xml, nosetests and pytest. However, as you can see in the sniffer, the header can vary slightly, so it's possible that there are other tools which generate XML cobertura files that won't be caught by this sniffer.

Maybe the sniffer should evolve to support some RegEx?

**Comment by donny-dont** [comment]
@fbcbarbosa I'm almost thinking that maybe there should be a coverage library similar to the caching library in Drone. Then maybe there's a way to run the transform separately. Still thinking about it, but that shouldn't matter for you.

**Review by donny-dont — APPROVED** [review]

**Pull request merged**
